#!/usr/bin/env zsh
#
# A theme based on trongrg theme
#  * RVM/Rbenv info shown on the right
#  * Git branch info on the left
#  * Single line prompt
#
# Authors:
# Trong Tran trongrg@gmail.com

pmodload 'helper'

function prompt_trongrg_pwd {
  local pwd="${PWD/#$HOME/~}"

  if [[ "$pwd" == (#m)[/~] ]]; then
    _prompt_trongrg_pwd="$MATCH"
    unset MATCH
  else
    _prompt_trongrg_pwd="${${${(@j:/:M)${(@s:/:)pwd}##.#?}:h}%/}/${pwd:t}"
  fi
}

function prompt_trongrg_precmd {
  setopt LOCAL_OPTIONS
  unsetopt XTRACE KSH_ARRAYS

  # Get Git repository information.
  if (( $+functions[git-info] )); then
    git-info
  fi

  # Format PWD.
  prompt_trongrg_pwd

  local prompt_line_1
  prompt_trongrg_setup_prompt

  PROMPT="$prompt_line_1$prompt_new_line$prompt_chars "
  SPROMPT='zsh: correct %F{red}%R%f to %F{green}%r%f [nyae]? '
}

prompt_trongrg_setup_prompt () {
  prompt_line_1="$prompt_line_1a$git_info"
}

function prompt_trongrg_setup {
  setopt LOCAL_OPTIONS
  unsetopt XTRACE KSH_ARRAYS
  prompt_opts=(cr percent subst)

  # Load required functions.
  autoload -Uz add-zsh-hook

  __PROMPT_COLORS=(
    "%F{81}"  # turquoise
    "%F{166}" # orange
    "%F{135}" # purple
    "%F{161}" # hotpink
    "%F{118}" # limegreen
  )

  __GIT_COLORS=(
    "%F{81}"  # branch
    "%F{118}" # ahead clean
    "%F{161}" # behind
    "%F{133}" # dirty
    "%F{082}" # unmerged added renamed
    "%F{160}" # deleted
    "%F{166}" # modified
    "%F{136}" # untracked
  )

  # git
  zstyle ':prezto:module:git:info:keys' format 'prompt' '($(coalesce "%b" "%p" "%c")%s%A%B%D%C%U)%a%d%m%u%r'

  zstyle ':prezto:module:git:info:branch' format "${__GIT_COLORS[1]}%b%f"
  zstyle ':prezto:module:git:info:ahead' format "${__GIT_COLORS[2]} ⬆%f"
  zstyle ':prezto:module:git:info:behind' format "${__GIT_COLORS[3]} ⬇%f"
  zstyle ':prezto:module:git:info:dirty' format "${__GIT_COLORS[4]} ✘%f"
  zstyle ':prezto:module:git:info:clean' format "${__GIT_COLORS[2]} ✔%f"
  zstyle ':prezto:module:git:info:unmerged' format "${__GIT_COLORS[5]} ═%f"

  zstyle ':prezto:module:git:info:added' format "${__GIT_COLORS[5]} ✚%f"
  zstyle ':prezto:module:git:info:deleted' format "${__GIT_COLORS[6]} ✖%f"
  zstyle ':prezto:module:git:info:modified' format "${__GIT_COLORS[7]} ✹%f"
  zstyle ':prezto:module:git:info:untracked' format "${__GIT_COLORS[8]} ✭%f"
  zstyle ':prezto:module:git:info:renamed' format "${__GIT_COLORS[5]} ➜%f"

  prompt_user_host="${__PROMPT_COLORS[3]}%n%f@${__PROMPT_COLORS[2]}%m%f"
  prompt_pwd="${__PROMPT_COLORS[5]}"'$_prompt_trongrg_pwd'"%f"

  prompt_line_1a="$prompt_user_host $prompt_pwd "
  prompt_chars=" %B${__PROMPT_COLORS[2]}❯${__PROMPT_COLORS[1]}❯${__PROMPT_COLORS[5]}❯%f%b"

  add-zsh-hook precmd prompt_trongrg_precmd
}

prompt_trongrg_setup "$@"
